"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-pf-*k_7kcrcjnlk+02##8y@%t=umba*v%hx%7!w80t1lkzt$#h'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'blog',
]

# ===== DRF 配置 =====
REST_FRAMEWORK = {
    # ---------- 认证 ----------
    # ⚠️ 顺序有意义：第一个认证器的 authenticate_header 决定未认证时返回 401 还是 403
    # RedisJWTAuthentication 继承自 JWTAuthentication，同样返回 'Bearer realm="api"' → 401 ✅
    # 如果 SessionAuthentication 排在第一位（它返回 None）→ 403
    'DEFAULT_AUTHENTICATION_CLASSES': [
        # 在 simplejwt 基础上多查一步 Redis 白名单，登出才能真正生效
        'blog.authentication.RedisJWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',  # 保留：可浏览 API 要用
    ],

    # ---------- 权限 ----------
    # 从 AllowAny 收紧：读接口公开，写接口必须登录
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],

    # ---------- 限流 ----------
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '60/minute',
        'user': '200/hour',
        'login': '5/minute',
    },

    # ---------- 分页 ----------
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,

    # ---------- 其他 ----------
    'DATETIME_FORMAT': '%Y-%m-%dT%H:%M:%S%z',
    'DEFAULT_FILTER_BACKENDS': [
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

# ===== 国际化 =====
LANGUAGE_CODE = 'zh-hans'  # 中文
TIME_ZONE = 'Asia/Shanghai'  # 中国时区

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}


# ===== JWT 配置 =====
SIMPLE_JWT = {
    # Token 有效期
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),   # 短命：被盗了损失也小
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),      # 长命：过期才需要重新登录

    # 刷新时是否轮换 refresh token
    # True 更安全（旧 refresh 失效），但前端要同步更新本地存的 refresh
    'ROTATE_REFRESH_TOKENS': False,

    # 认证头格式：Authorization: Bearer <token>
    # 想和 FastAPI 项目的 "Token xxx" 保持一致，就改成 ('Token',)
    'AUTH_HEADER_TYPES': ('Bearer',),

    # 用户标识放在哪个 claim
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
}

# ===== Redis 配置 =====
# 和 FastAPI 项目复用同一个 Redis 实例，用 db 号隔开：
#   FastAPI 项目 → db 0
#   Django 项目  → db 1
REDIS_HOST = 'localhost'
REDIS_PORT = 6379
REDIS_DB = 1
REDIS_PASSWORD = None       # 没设密码就保持 None